// Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package exporter

import (
	"context"
	"strings"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/sdk/instrumentation"
	"go.opentelemetry.io/otel/sdk/trace"
	oteltrace "go.opentelemetry.io/otel/trace"
)

var (
	// ADKAttributeKeyMap maps ADK internal attribute keys to standard GenAI keys.
	ADKAttributeKeyMap = map[string]string{
		"gcp.vertex.agent.llm_request":  "input.value",
		"gcp.vertex.agent.llm_response": "output.value",
		"gcp.vertex.agent.session_id":   "gen_ai.session.id",
		"gcp.vertex.agent.model":        "gen_ai.response.model",
		"gcp.vertex.agent.usage":        "gen_ai.usage",
	}

	// ADKTargetKeyAliases maps standard keys to their legacy or platform-specific aliases.
	ADKTargetKeyAliases = map[string][]string{
		"gen_ai.response.model": {"gcp.vertex.agent.model"},
		"gen_ai.usage":          {"gcp.vertex.agent.usage"},
	}
)

// isMatch returns true if we should keep the span in the final output.
// At this point, we filter out "call_llm" span generated by ADK-go with scope name is "gcp.vertex.agent".
func isMatch(span trace.ReadOnlySpan) bool {
	if span.InstrumentationScope().Name == "gcp.vertex.agent" {
		name := span.Name()
		if name == "call_llm" {
			return false
		}
	}
	return true
}

// ADKTranslatedExporter wraps a SpanExporter and remaps ADK attributes to standard fields.
type ADKTranslatedExporter struct {
	trace.SpanExporter
}

func (e *ADKTranslatedExporter) ExportSpans(ctx context.Context, spans []trace.ReadOnlySpan) error {
	translated := make([]trace.ReadOnlySpan, 0, len(spans))
	for _, s := range spans {
		if !isMatch(s) {
			continue
		}

		translated = append(translated, &translatedSpan{ReadOnlySpan: s})
	}

	if len(translated) == 0 {
		return nil
	}

	return e.SpanExporter.ExportSpans(ctx, translated)
}

// translatedSpan wraps a ReadOnlySpan and intercepts calls to Attributes().
type translatedSpan struct {
	trace.ReadOnlySpan
}

func (p *translatedSpan) Attributes() []attribute.KeyValue {
	attrs := p.ReadOnlySpan.Attributes()
	newAttrs := make([]attribute.KeyValue, 0, len(attrs))

	hasStandardUsage := false
	for _, kv := range attrs {
		if kv.Key == "gen_ai.usage" {
			hasStandardUsage = true
			break
		}
	}

	for _, kv := range attrs {
		key := string(kv.Key)

		// 1. Map ADK internal attributes if not already present in standard form
		if strings.HasPrefix(key, "gcp.vertex.agent.") {
			targetKey, ok := ADKAttributeKeyMap[key]
			if ok {
				// Avoid duplicates if Processor already mapped it
				alreadyMapped := false
				if !hasStandardUsage || targetKey != "gen_ai.usage" {
					for _, na := range newAttrs {
						if string(na.Key) == targetKey {
							alreadyMapped = true
							break
						}
					}
				}
				if !alreadyMapped {
					newAttrs = append(newAttrs, attribute.KeyValue{Key: attribute.Key(targetKey), Value: kv.Value})
				}
			}
			continue
		}

		// 2. Patch gen_ai.system if needed
		if key == "gen_ai.system" && kv.Value.AsString() == "gcp.vertex.agent" {
			kv = attribute.String("gen_ai.system", "veadk")
		}

		newAttrs = append(newAttrs, kv)
	}

	return newAttrs
}

func (p *translatedSpan) Parent() oteltrace.SpanContext {
	parent := p.ReadOnlySpan.Parent()
	sc := p.ReadOnlySpan.SpanContext()
	name := p.ReadOnlySpan.Name()
	traceID := sc.TraceID()

	// 1. Re-parent tool spans to the last 'call_llm' span
	if name == "execute_tool" || strings.HasPrefix(name, "execute_tool ") {
		if llmSC, ok := GetLLMSpanContext(traceID); ok {
			// Ensure we don't reparent the llm span to itself, which should not happen, but good for safety
			if llmSC.SpanID() != sc.SpanID() {
				return llmSC
			}
		}
	}

	// 2. Re-parent ADK internal spans (gcp.vertex.agent) to the current 'invoke_agent' span
	if p.ReadOnlySpan.InstrumentationScope().Name == "gcp.vertex.agent" {
		if agentSC, ok := GetAgentSpanContext(traceID); ok {
			// Ensure we don't reparent the agent span to itself
			if agentSC.SpanID() != sc.SpanID() {
				return agentSC
			}
		}
	}

	// 3. Re-parent 'invoke_agent' spans to 'invocation' if they are roots
	if !parent.IsValid() && (name == "invoke_agent" || strings.HasPrefix(name, "invoke_agent:") || strings.HasPrefix(name, "invoke_agent ")) {
		registryMutex.RLock()
		invSC, ok := invocationSpanMap[traceID]
		registryMutex.RUnlock()
		if ok {
			if invSC.SpanID() != sc.SpanID() {
				return invSC
			}
		}
	}

	return parent
}

func (p *translatedSpan) InstrumentationScope() instrumentation.Scope {
	scope := p.ReadOnlySpan.InstrumentationScope()
	// github.com/volcengine/veadk-go is the InstrumentationName defined in observability/constant.go
	if scope.Name == "gcp.vertex.agent" || scope.Name == "veadk" || scope.Name == "github.com/volcengine/veadk-go" {
		scope.Name = "openinference.instrumentation.veadk"
	}
	return scope
}

func (p *translatedSpan) InstrumentationLibrary() instrumentation.Scope {
	return p.InstrumentationScope()
}
