// Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package observability

import (
	"context"
	"strings"

	"github.com/volcengine/veadk-go/log"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/sdk/instrumentation"
	"go.opentelemetry.io/otel/sdk/trace"
	oteltrace "go.opentelemetry.io/otel/trace"
)

var (
	spanInvokeAgent = "invoke_agent"

	// ADKAttributeKeyMap maps ADK internal attribute keys to standard GenAI keys.
	ADKAttributeKeyMap = map[string]string{
		"gcp.vertex.agent.llm_request":  "input.value",
		"gcp.vertex.agent.llm_response": "output.value",
		"gcp.vertex.agent.session_id":   "gen_ai.session.id",
		"gcp.vertex.agent.model":        "gen_ai.response.model",
		"gcp.vertex.agent.usage":        "gen_ai.usage",
	}

	// ADKTargetKeyAliases maps standard keys to their legacy or platform-specific aliases.
	ADKTargetKeyAliases = map[string][]string{
		"gen_ai.response.model": {"gcp.vertex.agent.model"},
		"gen_ai.usage":          {"gcp.vertex.agent.usage"},
	}
)

// isMatch returns true if we should keep the span in the final output.
// At this point, we filter out "call_llm" span generated by ADK-go with scope name is "gcp.vertex.agent".
func isMatch(span trace.ReadOnlySpan) bool {
	if span.InstrumentationScope().Name == "gcp.vertex.agent" {
		name := span.Name()
		if name == "call_llm" {
			return false
		}
	}
	return true
}

// ADKTranslatedExporter wraps a SpanExporter and remaps ADK attributes to standard fields.
type ADKTranslatedExporter struct {
	trace.SpanExporter
}

func (e *ADKTranslatedExporter) ExportSpans(ctx context.Context, spans []trace.ReadOnlySpan) error {
	translated := make([]trace.ReadOnlySpan, 0, len(spans))
	for _, s := range spans {
		if !isMatch(s) {
			continue
		}

		ts := &translatedSpan{ReadOnlySpan: s}
		translated = append(translated, ts)

		// 1. Logic stitching via ToolCallID
		toolCallID := ""
		for _, kv := range s.Attributes() {
			if string(kv.Key) == "gen_ai.tool.call.id" {
				toolCallID = kv.Value.AsString()
				break
			}
		}

		if toolCallID != "" {
			if manualParentSC, ok := getManualParentContextByToolCallID(toolCallID); ok {
				// We found a match! Record this TraceID mapping to align other spans in the same trace (like merged spans)
				registerTraceMapping(s.SpanContext().TraceID(), manualParentSC.TraceID())
				log.Debug("Matched tool via ToolCallID, established TraceID mapping",
					"tool_call_id", toolCallID,
					"internal_trace_id", s.SpanContext().TraceID().String(),
					"manual_trace_id", manualParentSC.TraceID().String(),
				)
			}
		}

		// Debug logging for execute_tool
		if strings.Contains(s.Name(), "execute_tool") {
			sc := ts.SpanContext()
			parent := ts.Parent()
			log.Debug("Translating tool span",
				"name", s.Name(),
				"orig_span_id", s.SpanContext().SpanID().String(),
				"orig_trace_id", s.SpanContext().TraceID().String(),
				"new_trace_id", sc.TraceID().String(),
				"orig_parent_id", s.Parent().SpanID().String(),
				"new_parent_id", parent.SpanID().String(),
			)
		}
	}

	if len(translated) == 0 {
		return nil
	}

	return e.SpanExporter.ExportSpans(ctx, translated)
}

// translatedSpan wraps a ReadOnlySpan and intercepts calls to Attributes().
type translatedSpan struct {
	trace.ReadOnlySpan
}

func (p *translatedSpan) Attributes() []attribute.KeyValue {
	attrs := p.ReadOnlySpan.Attributes()
	newAttrs := make([]attribute.KeyValue, 0, len(attrs))

	hasStandardUsage := false
	for _, kv := range attrs {
		if kv.Key == "gen_ai.usage" {
			hasStandardUsage = true
			break
		}
	}

	for _, kv := range attrs {
		key := string(kv.Key)

		// 1. Map ADK internal attributes if not already present in standard form
		if strings.HasPrefix(key, "gcp.vertex.agent.") {
			targetKey, ok := ADKAttributeKeyMap[key]
			if ok {
				// Avoid duplicates if Processor already mapped it
				alreadyMapped := false
				if !hasStandardUsage || targetKey != "gen_ai.usage" {
					for _, na := range newAttrs {
						if string(na.Key) == targetKey {
							alreadyMapped = true
							break
						}
					}
				}
				if !alreadyMapped {
					newAttrs = append(newAttrs, attribute.KeyValue{Key: attribute.Key(targetKey), Value: kv.Value})
				}
			}
			continue
		}

		// 2. Patch gen_ai.system if needed
		if key == "gen_ai.system" && kv.Value.AsString() == "gcp.vertex.agent" {
			kv = attribute.String("gen_ai.system", "veadk")
		}

		newAttrs = append(newAttrs, kv)
	}

	return newAttrs
}

func (p *translatedSpan) SpanContext() oteltrace.SpanContext {
	sc := p.ReadOnlySpan.SpanContext()

	// [Thin Layer] TraceID Correction.
	// 1. Try ToolCallID mapping (most precise)
	toolCallID := ""
	for _, kv := range p.ReadOnlySpan.Attributes() {
		if string(kv.Key) == "gen_ai.tool.call.id" {
			toolCallID = kv.Value.AsString()
			break
		}
	}

	if manualParentSC, ok := getManualParentContextByToolCallID(toolCallID); ok {
		return oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
			TraceID:    manualParentSC.TraceID(),
			SpanID:     sc.SpanID(),
			TraceFlags: sc.TraceFlags(),
			TraceState: sc.TraceState(),
			Remote:     sc.IsRemote(),
		})
	}

	// 2. Try global TraceID mapping (for spans in the same trace without their own tool_call_id)
	if manualTID, ok := getManualTraceID(sc.TraceID()); ok {
		return oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
			TraceID:    manualTID,
			SpanID:     sc.SpanID(),
			TraceFlags: sc.TraceFlags(),
			TraceState: sc.TraceState(),
			Remote:     sc.IsRemote(),
		})
	}

	// 3. Fallback to Tool SpanID mapping
	if manualParentSC, ok := getManualParentContextForTool(sc.SpanID()); ok {
		return oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
			TraceID:    manualParentSC.TraceID(),
			SpanID:     sc.SpanID(),
			TraceFlags: sc.TraceFlags(),
			TraceState: sc.TraceState(),
			Remote:     sc.IsRemote(),
		})
	}

	return sc
}

func (p *translatedSpan) Parent() oteltrace.SpanContext {
	parent := p.ReadOnlySpan.Parent()
	sc := p.ReadOnlySpan.SpanContext()

	// 1. Precise Re-parenting based on internal ParentID mapping
	if parent.IsValid() {
		if manualSC, ok := getManualParentContext(parent.SpanID()); ok {
			return manualSC
		}
	}

	// 2. Try ToolCallID mapping (for tool spans that lost parent context)
	toolCallID := ""
	for _, kv := range p.ReadOnlySpan.Attributes() {
		if string(kv.Key) == "gen_ai.tool.call.id" {
			toolCallID = kv.Value.AsString()
			break
		}
	}
	if manualParentSC, ok := getManualParentContextByToolCallID(toolCallID); ok {
		return manualParentSC
	}

	// 3. Fallback: Re-parent root spans if we have a direct mapping for this span ID.
	if !parent.IsValid() {
		if manualSC, ok := getManualParentContextForTool(sc.SpanID()); ok {
			return manualSC
		}
	}

	return parent
}

func (p *translatedSpan) InstrumentationScope() instrumentation.Scope {
	scope := p.ReadOnlySpan.InstrumentationScope()
	// github.com/volcengine/veadk-go is the InstrumentationName defined in observability/constant.go
	if scope.Name == "gcp.vertex.agent" || scope.Name == "veadk" || scope.Name == "github.com/volcengine/veadk-go" {
		scope.Name = "openinference.instrumentation.veadk"
	}
	return scope
}

func (p *translatedSpan) InstrumentationLibrary() instrumentation.Scope {
	return p.InstrumentationScope()
}
